OfficeDev/TrainingContent

- O3657/O3657-2 Creating Client Side Only Apps with Angular, ADAL and Office 365 APIs/README.md
This is a placeholder for the completed module coming later this week.
> Added temp readme for O3657-2

- O3658/02 Managing site settings using app model/Demos/JavaScriptInjection/JavaScriptInjectionWeb/Scripts/scenario1.js
Small fix based on feedback in Yammer group
> Proper MDS implementation for the javascript injection sample

- O3657/O3657-1 Deep dive into building standalone AngularJS web applications with Bootstrap for Office 365/Completed Projects/AngularCRM_Final/AngularCRM/App/controllers.js
- O3657/O3657-1 Deep dive into building standalone AngularJS web applications with Bootstrap for Office 365/Demos/AngularCRM/AngularCRM/App/controllers.js
- O3657/O3657-1 Deep dive into building standalone AngularJS web applications with Bootstrap for Office 365/Lab.md
Updates to fix delete customer bug in Angular lab. 
1) Updated controllers.js in lab solution with correct code
2) Updated controllers.js in demo solution (Demos\AngularCRM) with correct code
3) Updated lab.md with instructions to add corrected code to home controller
> Angular Lab Bug Fix - delete not working

- O3655/O3655-5 Embedding Marketing in Your Code/Demos/AppointmentScheduler/AppointmentSchedulerWeb/AppointmentSchedulerWeb.csproj
- O3655/O3655-5 Embedding Marketing in Your Code/Demos/AppointmentScheduler/AppointmentSchedulerWeb/Third Party Notices.txt
Adding third party legal notices
> Third Party Notices

- O3651/O3651-3 Getting started with Apps for SharePoint/Lab.md
Removed step14 per discussion thread. 
Also reformatted markdown to be more correct than originally authored.
> Fix for issue #91

- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Controllers/OneDriveNewApiController.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Data/OneDriveWebContext.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Data/OneDriveWebInitializer.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Models/JsonHelpers/FolderContents.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Models/OneDriveNewApiRepository.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/OneDriveWeb.csproj
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Views/OneDriveNewApi/Index.cshtml
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Views/Shared/_Layout.cshtml
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Web.config
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Demos/Office365Files.Demo.md
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Lab Files/FolderContents.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Lab Files/OneDriveWebContext.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Lab Files/OneDriveWebInitializer.cs
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Lab.md
Reformatted lab to make ex2 more of a multi-step exercise than multiple exercises; added new exercise demonstrating how to use the v2.0 REST API for OD4B (that will mirror the OD4C REST API).
> Updated Module: O3653-3 - Deep Dive into Office 365 APIs for OneDrive for Business

- O3651/O3651-5 Getting started with Office 365 APIs/Demos/ReadMe.md
- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Lab.md
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab.md
- O3657/O3657-2 Creating Client Side Only Apps with Angular, ADAL and Office 365 APIs/Completed Project/README.md
- O3657/O3657-2 Creating Client Side Only Apps with Angular, ADAL and Office 365 APIs/Lab.md
Feedback and issues discovered during Office 365 Dev Camps
> Update to readme and lab descriptions

- O3657/O3657-2 Creating Client Side Only Apps with Angular, ADAL and Office 365 APIs/Lab.md
> corrected typos in lab

- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Completed project/O365-Win-Profile.sln
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab Files/O365-Win-Profile.sln
> O3653 8 sln fix

- O3651/O3651-5 Getting started with Office 365 APIs/Lab.md
> O3651-5: Fix for issue #222.

- O3653/O3653-14 Deep Dive into Office 365 APIs for Contacts/Lab.md
Fixing link to SQL server DB connection error resolution instructions.
> Fixing link to SQL server DB connection error resolution instructions.

- O3653/O3653-1 Deep Dive into Azure AD with the Office 365 APIs/Lab.md
O3653-1: Updated link text for the LabFiles folder.
> O3653-1: Updated link text for the LabFiles folder.

- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Completed project/AuthenticationHelper.cs
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Completed project/UserOperations.cs
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab Files/AuthenticationHelper.cs
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab Files/UserOperations.cs
O3653-8: Committing files with renamed variables again to address issue #208.
> O3653-8: Committing files with renamed variables again to address issue #208.

- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab.md
O3653-8: Modified lab.MD to fix issue #244.
> O3653-8: Modified lab.MD to fix issue #244.

- O3653/O3653-14 Deep Dive into Office 365 APIs for Contacts/Lab.md
O3653-14: Modified lab.MD to update terminology, links to files, and correct a few small text issues.
> O3653-14: Modified lab.MD to update terminology, links to files, and correct a few small text issues.

- O3653/O3653-1 Deep Dive into Azure AD with the Office 365 APIs/Lab.md
- O3653/O3653-12 Deep dive into the Office 365 Video API/Lab.md
- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab.md
- O3654/O3654-1 Deep dive into native Universal Windows App Development with Office 365 APIs/Lab.md
O3653-1, O3653-8, O3653-12, O3654-1: Added instruction steps to hands on labs to update Nuget packages.  This closes issue #142.
> O3653-1, O3653-8, O3653-12, O3654-1: Added instruction steps to hands on labs to update Nuget packages.  This closes issue #142.

- O3651/O3651-5 Getting started with Office 365 APIs/Lab.md
- O3652/O3652-7 Deep Dive into Security and OAuth/Completed Projects/Exercise03/Web.config
- O3652/O3652-7 Deep Dive into Security and OAuth/Completed Projects/Exercise03/packages.config
- O3652/O3652-7 Deep Dive into Security and OAuth/Lab.md
- O3652/O3652-7 Deep Dive into Security and OAuth/Starter Project/Web.config
- O3652/O3652-7 Deep Dive into Security and OAuth/Starter Project/packages.config
O3651-5: Lab.md updates to addresses issues #275, #276, and #277.
O3652-7: Remove duplicate Nuget packages for starter and completed project exercise 3 and update lab.md.  Fixed issue #270.
> O3651-5 & O3652-7

- O3653/O3653-3 Deep Dive into Office 365 APIs for OneDrive for Business/Completed Projects/Exercise02/OneDriveWeb/OneDriveWeb.csproj
> Update netfx version

- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab.md
O3653-8: Updated lab.md. This fixes issue #280.
> O3653-8: Updated lab.md.  This fixes issue #280.

- O3653/O3653-8 Deep Dive into the Office 365 Unified API/Lab.md
> Corrected endpoint property name in lab steps.

- Teams/05 Microsoft Teams apps - Advanced Techniques/Lab.md
- Teams/05 Microsoft Teams apps - Advanced Techniques/Readme.md
While recording sceencast, found a few minor bugs & typos in the lab that this commit resolves.
> Bug+typo fix for Teams module #05

- .gitignore
- Graph/README.md
This adds a TOC to the Microsoft Graph section of the repo mirroring the TOC's that other sections in the repo have.
> Graph module toc add

- OfficeAddin/01 Building Add-ins for Microsoft Word/README.md
Validate lab & tutorial steps work as designed with no regression in last few months.
> OfficeAddins - Module 1: Fy2019Q2 Quarterly refresh

- ConnectorActionableMsgs/02 Cards and Actions/Demos/03-Expense-Approval/ExpenseApproval/Controllers/ExpenseController.cs
- ConnectorActionableMsgs/02 Cards and Actions/Demos/03-Expense-Approval/ExpenseApproval/Helpers/ActionableMessageHelper.cs
- ConnectorActionableMsgs/02 Cards and Actions/Demos/03-Expense-Approval/ExpenseApproval/Models/ValidationModel.cs
- ConnectorActionableMsgs/02 Cards and Actions/Lab.md
- ConnectorActionableMsgs/02 Cards and Actions/LabFiles/ActionableMessageHelper.cs
- ConnectorActionableMsgs/02 Cards and Actions/LabFiles/ExpenseController.cs
- ConnectorActionableMsgs/02 Cards and Actions/README.md
- added copyright to edited files
- updated slides & code samples to work against all current deps
> Connectors - Module 2: FY2019Q3 Quarterly refresh

- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/app/web/auth-end.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/app/web/auth-start.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/README.md
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/README.md
- fix typos
- update teams JS SDK CDN location
- closes #627, closes #632
> FY2020Q2 content refresh: "MSTeams - M30"

- Teams/02 Tabs and Connectors/Demos/01-tabs/officedev-talent-management/Tabs/candidates.html
- Teams/02 Tabs and Connectors/Demos/01-tabs/officedev-talent-management/Tabs/channelconfig.html
- Teams/02 Tabs and Connectors/Demos/01-tabs/officedev-talent-management/Tabs/channeltab.html
- Teams/02 Tabs and Connectors/Demos/02-connector/officedev-talent-management/Connector/connectorconfig.html
- Teams/02 Tabs and Connectors/Demos/02-connector/officedev-talent-management/Tabs/candidates.html
- Teams/02 Tabs and Connectors/Demos/02-connector/officedev-talent-management/Tabs/channelconfig.html
- Teams/02 Tabs and Connectors/Demos/02-connector/officedev-talent-management/Tabs/channeltab.html
- Teams/02 Tabs and Connectors/LabFiles/Connector/connectorconfig.html
- Teams/02 Tabs and Connectors/LabFiles/Tabs/candidates.html
- Teams/02 Tabs and Connectors/LabFiles/Tabs/channelconfig.html
- Teams/02 Tabs and Connectors/LabFiles/Tabs/channeltab.html
- Teams/02 Tabs and Connectors/Readme.md
- closes #637, closes #638, closes #640, closes #641, closes #642
> FY2020Q2 content refresh: "MSTeams - M02"

- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/Candidates.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/auth-end.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/auth-start.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/channelconfig.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/channeltab.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/hiringTeam.html
- Teams/03 Authentication/Demos/01-add-authentication-tab/solution/officedev-talent-management/Tabs/hiringTeamConfig.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/Candidates.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/auth-end.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/auth-start.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/auth.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/channelconfig.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/channeltab.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/hiringTeam.html
- Teams/03 Authentication/Demos/02-add-authentication-bot/solution/officedev-talent-management/Tabs/hiringTeamConfig.html
- Teams/03 Authentication/Lab.md
- Teams/03 Authentication/LabFiles/Starter/officedev-talent-management/Tabs/Candidates.html
- Teams/03 Authentication/LabFiles/Starter/officedev-talent-management/Tabs/channelconfig.html
- Teams/03 Authentication/LabFiles/Starter/officedev-talent-management/Tabs/channeltab.html
- Teams/03 Authentication/LabFiles/auth-end.html
- Teams/03 Authentication/LabFiles/auth-start.html
- Teams/03 Authentication/LabFiles/hiringTeam.html
- Teams/03 Authentication/LabFiles/hiringTeamConfig.html
- Teams/03 Authentication/Readme.md
- closes #633, closes #636, closes #639, closes #643, closes #644
> FY2020Q2 content refresh: "MSTeams - M03"

- Identity/02 Application Types/README.md
- Identity/03 Permission and Consent Framework/README.md
- Identity/README.md
- Teams/50 Task Modules/README.md
- add screencasts links to new modules
- update url to MS Identity modules in MS Learn
> FY2020Q2 new module screencast add

- Identity/03 Permission and Consent Framework/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/package-lock.json
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/package.json
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/server.js
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/web/index.html
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/README.md
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/package-lock.json
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/package.json
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/server.js
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/web/index.html
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Helpers/AuthHandler.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Helpers/MsalAuthenticationProvider.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Program.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/graphdaemon.csproj
- updated screenshots where necessary
- updated steps & typos where necessary
> FY2020Q3 content refresh: Identity M03

- Identity/02 Application Types/README.md
- Identity/02 Application Types/demos/01-spa/README.md
- Identity/02 Application Types/demos/01-spa/index.html
- Identity/02 Application Types/demos/01-spa/package-lock.json
- Identity/02 Application Types/demos/01-spa/package.json
- Identity/02 Application Types/demos/01-spa/server.js
- Identity/02 Application Types/demos/02-webapp/02-webapp.csproj
- Identity/02 Application Types/demos/02-webapp/Controllers/UserController.cs
- Identity/02 Application Types/demos/02-webapp/Helpers/GraphUserAccount.cs
- Identity/02 Application Types/demos/02-webapp/README.md
- Identity/02 Application Types/demos/02-webapp/Startup.cs
- Identity/02 Application Types/demos/02-webapp/Views/Shared/_Layout.cshtml
- Identity/02 Application Types/demos/02-webapp/Views/User/Index.cshtml
- Identity/02 Application Types/demos/02-webapp/appsettings.Development.json
- Identity/02 Application Types/demos/03-daemon-service-app/Helpers/AuthHandler.cs
- Identity/02 Application Types/demos/03-daemon-service-app/Helpers/MsalAuthenticationProvider.cs
- Identity/02 Application Types/demos/03-daemon-service-app/Program.cs
- Identity/02 Application Types/demos/03-daemon-service-app/README.md
- Identity/02 Application Types/demos/03-daemon-service-app/graphdaemon.csproj
- updated screenshots where necessary
- updated steps & typos where necessary
> FY2020Q3 content refresh: Identity M02

- Identity/03 Permission and Consent Framework/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/web/index.html
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/web/index.html
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/README.md
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/graphdaemon.csproj
- update pictures, resources, and steps to account for dependency updates
> MSIdentity module "permissions & consent" - FY2021Q1 refresh

- Identity/02 Application Types/README.md
- Identity/02 Application Types/demos/01-spa/index.html
- update section 1 to leverage auth code flow in MSAL.js from implicit
- update slides
- update code sample
> msidentity app types module: migrate implicit to auth code flow

- Identity/02 Application Types/README.md
- Identity/02 Application Types/demos/01-spa/README.md
- Identity/02 Application Types/demos/01-spa/index.html
- Identity/02 Application Types/demos/02-webapp/Controllers/UserController.cs
- Identity/02 Application Types/demos/02-webapp/IdentityWeb.csproj
- Identity/02 Application Types/demos/03-daemon-service-app/Helpers/MsalAuthenticationProvider.cs
- Identity/02 Application Types/demos/03-daemon-service-app/Program.cs
- Identity/02 Application Types/demos/03-daemon-service-app/graphdaemon.csproj
- update demos to reflect latest dependencies
- update lab steps to match current dependencies
- update image names per reviewer feedback
- Any IDs, company names, or people names in lab steps or screenshots are fictitious and were generated by Microsoft-created demo tenants.
> MSFT identity - AppTypes Module - FY21Q2 refresh

- Identity/03 Permission and Consent Framework/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/web/index.html
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/README.md
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/web/index.html
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Helpers/MsalAuthenticationProvider.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/README.md
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/graphdaemon.csproj
- update demos to reflect latest dependencies
- update lab steps to match current dependencies
- update image names per reviewer feedback
- Any IDs, company names, or people names in lab steps or screenshots are fictitious and were generated by Microsoft-created demo tenants.
> MSFT identity - PermissionConsentFw Module - FY21Q2 refresh

- Identity/03 Permission and Consent Framework/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/package-lock.json
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/web/index.html
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/package-lock.json
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/web/index.html
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Helpers/MsalAuthenticationProvider.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/README.md
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/graphdaemon.csproj
> Identity - PermissionsConsent - FY21Q3 refresh

- Identity/01 Getting Started Microsoft Identity/README.md
- Identity/01 Getting Started Microsoft Identity/demos/01-spa/package-lock.json
- Identity/01 Getting Started Microsoft Identity/demos/01-spa/web/index.html
- Identity/01 Getting Started Microsoft Identity/demos/02-aspnetcore-multitorg/AccountTypesMultiOrg.csproj
- Identity/01 Getting Started Microsoft Identity/demos/02-aspnetcore-multitorg/Views/Home/Index.cshtml
- Identity/01 Getting Started Microsoft Identity/demos/02-aspnetcore-singleorg/AccountTypesSingleOrg.csproj
- Identity/01 Getting Started Microsoft Identity/demos/03-aspnetcode-b2b/TopologyOptions.csproj
- Identity/01 Getting Started Microsoft Identity/demos/03-aspnetcode-b2b/Views/Home/Index.cshtml
> FY21Q4 refresh - getting-started-identity

- Identity/03 Permission and Consent Framework/README.md
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/package-lock.json
- Identity/03 Permission and Consent Framework/demos/01-understand-permissions-consent/web/index.html
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/package-lock.json
- Identity/03 Permission and Consent Framework/demos/02-static-dynamic-permissions/web/index.html
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/Program.cs
- Identity/03 Permission and Consent Framework/demos/03-app-permissions/graphdaemon.csproj
> FY21Q4 refresh - identity-permissions-consent

- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/03-teams/src/client/youTubePlayerTab/YouTubePlayerTab.tsx
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/README.md
> FY22Q1 refresh - adaptive-cards-create-engaging-messages

- Teams/40 Conversational Bots/Demos/01-learn-msteams-bots/.env.example
- Teams/40 Conversational Bots/Demos/01-learn-msteams-bots/.yo-rc.json
- Teams/40 Conversational Bots/Demos/01-learn-msteams-bots/package.json
- Teams/40 Conversational Bots/Demos/01-learn-msteams-bots/src/manifest/manifest.json
- Teams/40 Conversational Bots/Demos/01-learn-msteams-bots/src/server/conversationalBot/ConversationalBot.ts
- Teams/40 Conversational Bots/Demos/02-learn-msteams-bots/.env.example
- Teams/40 Conversational Bots/Demos/02-learn-msteams-bots/.yo-rc.json
- Teams/40 Conversational Bots/Demos/02-learn-msteams-bots/package.json
- Teams/40 Conversational Bots/Demos/03-learn-msteams-bots/.env.example
- Teams/40 Conversational Bots/Demos/03-learn-msteams-bots/.yo-rc.json
- Teams/40 Conversational Bots/Demos/03-learn-msteams-bots/package.json
- Teams/40 Conversational Bots/README.md
> FY22Q1 refresh - msteams-conversation-bots

- Teams/20 Messaging Extensions/Demos/01-msteams-msgext/package.json
- Teams/20 Messaging Extensions/Demos/01-msteams-msgext/src/manifest/manifest.json
- Teams/20 Messaging Extensions/Demos/02-msteams-msgext/package.json
- Teams/20 Messaging Extensions/Demos/02-msteams-msgext/src/manifest/manifest.json
- Teams/20 Messaging Extensions/Demos/03-msteams-msgext/package.json
- Teams/20 Messaging Extensions/Demos/03-msteams-msgext/src/manifest/manifest.json
- Teams/20 Messaging Extensions/README.md
> FY22Q1 refresh - msteams-messaging-extensions

- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/.env.EXAMPLE
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/.yo-rc.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/package.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/client/ssoTab/SsoTab.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/manifest/manifest.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/.env
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/.yo-rc.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/package.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/client/Bot/SsoBotTab.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/client/client.ts
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/manifest/manifest.json
- Teams/80 Using Single Sign-On with Microsoft Teams/README.md
> FY22Q1 refresh - msteams-sso

- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/.env.EXAMPLE
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/.yo-rc.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/package.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/client.ts
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabConfig.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabRemove.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/server/server.ts
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/.env.EXAMPLE
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/.yo-rc.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/package.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabConfig.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabRemove.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/server/server.ts
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/.env
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/.yo-rc.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/package.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/server/server.ts
- Teams/70 Microsoft Graph Teamwork Endpoint/README.md
> FY22Q1 refresh - msteams-teamwork-endpoint

- Teams/50 Task Modules/README.md
- Teams/60 Webhooks O365 Connectors/Demos/01-webhooks/.env.example
- Teams/60 Webhooks O365 Connectors/Demos/01-webhooks/.yo-rc.json
- Teams/60 Webhooks O365 Connectors/Demos/01-webhooks/package.json
- Teams/60 Webhooks O365 Connectors/Demos/01-webhooks/src/manifest/manifest.json
- Teams/60 Webhooks O365 Connectors/Demos/03-o365-connector/.env.example
- Teams/60 Webhooks O365 Connectors/Demos/03-o365-connector/.yo-rc.json
- Teams/60 Webhooks O365 Connectors/Demos/03-o365-connector/package.json
- Teams/60 Webhooks O365 Connectors/Demos/03-o365-connector/src/client/myFirstTeamsConnector/MyFirstTeamsConnectorConfig.tsx
- Teams/60 Webhooks O365 Connectors/Demos/03-o365-connector/src/server/myFirstTeamsConnector/MyFirstTeamsConnector.ts
- Teams/60 Webhooks O365 Connectors/README.md
> FY22Q1 refresh - msteams-webhooks-connectors

- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/01 Mail Add-ins Basics/package-lock.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/01 Mail Add-ins Basics/package.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/01 Mail Add-ins Basics/tsconfig.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/02 Add-in Commands and Dialogs/package-lock.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/02 Add-in Commands and Dialogs/package.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/02 Add-in Commands and Dialogs/tsconfig.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/03 Task Pane Experiences/package-lock.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/03 Task Pane Experiences/package.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/Demos/03 Task Pane Experiences/tsconfig.json
- OfficeAddin/04 Building Add-ins for Microsoft Outlook/README.md
> FY22Q2 refresh - office-add-ins-outlook

- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/README.md
> FY22Q2 refresh - msteams-teamwork-endpoint

- Teams/70 Microsoft Graph Teamwork Endpoint/README.md
> FY22Q3 refresh - msteams-teamwork-endpoint

- Teams/80 Using Single Sign-On with Microsoft Teams/README.md
> FY22Q3 refresh - msteams-sso

- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/README.md
> FY22Q3 refresh - msteams-embedded-web-experiences

- Teams/40 Conversational Bots/README.md
> FY22Q3 refresh - msteams-conversation-bots

- OfficeAddin/04 Building Add-ins for Microsoft Outlook/README.md
- implement changes per Acrolinx feedback
> FY22Q4 refresh - office-add-ins-outlook

- OfficeAddin/02 Building Add-ins for Microsoft Excel/README.md
- implement changes per Acrolinx feedback
> FY22Q4 refresh - office-add-ins-excel

- OfficeAddin/06 Using Single Sign-On with Office Add-ins/README.md
- implement changes per Acrolinx feedback
> FY22Q4 refresh - office-add-ins-sso

- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/02-outlook/send-email-card-dotnetcore/Helpers/MsalAuthenticationProvider.cs
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/02-outlook/send-email-card-dotnetcore/Program.cs
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/02-outlook/send-email-card-dotnetcore/email-body.html
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/02-outlook/send-email-card-dotnetcore/graphconsoleapp.csproj
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/README.md
- OfficeAddin/01 Building Add-ins for Microsoft Word/README.md
- OfficeAddin/06 Using Single Sign-On with Office Add-ins/README.md
- implement changes per Acrolinx feedback
> FY22Q4 refresh - adaptive-cards-create-engaging-messages

- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/Demos/03-teams/src/client/youTubePlayerTab/YouTubePlayerTab.tsx
- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/README.md
> FY23Q1 refresh - adaptive-cards-create-engaging-messages

- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabConfig.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabRemove.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/01 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabConfig.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabRemove.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/02 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTab.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabConfig.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/client/msGraphTeamworkTab/MsGraphTeamworkTabRemove.tsx
- Teams/70 Microsoft Graph Teamwork Endpoint/Demos/03 - learn-msteams-teamwork/src/manifest/manifest.json
- Teams/70 Microsoft Graph Teamwork Endpoint/README.md
> FY23Q1 refresh - msteams-teamwork-endpoint

- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/client/ssoTab/SsoTab.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/client/ssoTab/SsoTabConfig.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/client/ssoTab/SsoTabRemove.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/01-learn-msteams-sso-tab/src/manifest/manifest.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/client/Bot/SsoBotTab.tsx
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/manifest/manifest.json
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/server/SsoBot/SsoBot.ts
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/server/SsoBot/dialogs/mainDialog.ts
- Teams/80 Using Single Sign-On with Microsoft Teams/Demos/02-learn-msteams-sso-bot/src/server/SsoBot/helpers/SsoOauthHelper.ts
- Teams/80 Using Single Sign-On with Microsoft Teams/README.md
> FY23Q1 refresh - msteams-sso

- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/01-learn-msteams-tabs/src/client/learnPersonalTab/LearnPersonalTab.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/src/client/configMathTab/ConfigMathTab.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/src/client/configMathTab/ConfigMathTabConfig.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/src/client/configMathTab/ConfigMathTabRemove.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/src/client/learnPersonalTab/LearnPersonalTab.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/src/manifest/manifest.json
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/client/learnAuthTab/LearnAuthTab.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/client/learnAuthTab/LearnAuthTabConfig.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/client/learnAuthTab/LearnAuthTabRemove.tsx
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/manifest/manifest.json
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/public/auth-end.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/public/auth-start.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/public/index.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/public/privacy.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/03-auth-tab/src/public/tou.html
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/README.md
- updated to use Teams Developer Portal
- updated to use Teams JS v2 SDK
> FY23Q1 refresh - embedded-web-experiences

- Teams/40 Conversational Bots/Demos/02-learn-msteams-bots/src/server/conversationalBot/dialogs/mainDialog.ts
- Teams/40 Conversational Bots/README.md
> FY23Q1 refresh - msteams-conversation-bots

- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/03-learn-msteams-meetings/package-lock.json
- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/03-learn-msteams-meetings/src/client/standUpAgendaTab/StandUpAgendaTab.tsx
- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/03-learn-msteams-meetings/src/server/api/StandupAgendaRouter.ts
- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/03-learn-msteams-meetings/src/server/server.ts
- Teams/90 Create interactive meeting apps for Microsoft Teams/README.md
> FY23Q2 refresh - msteams-meetings-apps

- ConnectorActionableMsgs/Engaging messages for Outlook and Teams/README.md
> FY23Q3 refresh - adaptive-cards-create-engaging-messages

- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/01-learn-msteams-meetings/package-lock.json
- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/02-learn-msteams-meetings/package-lock.json
- Teams/90 Create interactive meeting apps for Microsoft Teams/Demos/03-learn-msteams-meetings/package-lock.json
- Teams/90 Create interactive meeting apps for Microsoft Teams/README.md
> FY23Q3 refresh - msteams-meetings-apps

- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/01-learn-msteams-tabs/package-lock.json
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/Demos/02-learn-msteams-tabs/package-lock.json
- Teams/30 Create Embedded Web Experiences with Tabs for Microsoft Teams/README.md
> FY23Q3 refresh - msteams-embedded-web-experiences
